config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      get 'hello', to: 'root#hello'
      resources :nodes,only: [:index,:show] do
        collection do
          get :materials
          get :models
        end
      end
      resources :materials,only:[:index,:show]
      resources :models,only:[:index,:show]
    end
  end

  root to: 'materials#index'
  get 'materials/material_category:id',to: 'materials#node_category', as: 'node_category_materials'
  get 'materials/node:id', to: 'materials#node', as: 'node_materials'
  get 'models/model_category:id',to: 'models#node_category', as: 'node_category_models'
  get 'models/node:id', to: 'models#node', as: 'node_models'
  resources :materials,only:[:index,:new,:create] do
    collection do
      get :all
      get :search
      get :find_by_ids
    end
  end
  resources :models,only:[:index,:new,:create] do
    collection do
      get :all
      get :search
      get :find_by_ids
    end
  end
  resources :nodes,only:[:index]
  resources :categories,only:[:index]
  resources :home,only:[:index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  begin
    ActiveAdmin.routes(self) 
  rescue Exception => e
    
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount PgHero::Engine, at: "pghero"
  mount ExceptionTrack::Engine => "/exception-track"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/base_model.rb
module BaseModel
	extend ActiveSupport::Concern

	included do
		scope :recent, -> { order(id: :desc) }
		scope :exclude_ids, ->(ids) { where.not(id: ids.map(&:to_i)) }
		scope :by_week, -> { where("created_at > ?", 7.days.ago.utc) }
		scope :find_by_ids, ->(ids) { include_column_ids('id', ids) }
  	scope :include_column_ids, ->(column, ids) { ids.empty? ? all : where(column => ids) }
		
		delegate :url_helpers, to: 'Rails.application.routes'
	end
	
end

app/models/concerns/cache_version.rb
# 用于记录特定的 cache version
# 比如:
#    记录最后更新 置顶话题的时间,以用于作为自动变换置顶那个 cache 的 key，以达到自动过期的目的
# 用法例子:
#   以上面个场景为例
#   Topic after_suggest ->
#   CacheVersion.topic_last_suggested_at = Time.now
#  View 里面 <% cache("topic/index/sidebar_suggest:#{CacheVersion.topic_last_suggested_at}") do %><% end %>
class CacheVersion
  def self.method_missing(method, *args)
    method_name = method.to_s
    super(method, *args)
  rescue NoMethodError
    if method_name.match?(/=$/)
      var_name = method_name.sub('='.freeze, ''.freeze)
      key = CacheVersion.mk_key(var_name)
      value = args.first.to_s
      # save
      Rails.cache.write(key, value)
    else
      key = CacheVersion.mk_key(method)
      Rails.cache.read(key)
    end
  end

  def self.mk_key(key)
    "cache_version:#{key}"
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    after_commit on: [:create, :update] do
      SearchIndexer.perform_later('index', self.class.name, self.id)
    end
    
    after_destroy on: :destroy do
      SearchIndexer.perform_later('delete', self.class.name, self.id)
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
	include Searchable
  include BaseModel
  belongs_to :node
  mount_uploader :texture,PhotoUploader,:on=>:filename
  mount_uploader :thumbnail,PhotoUploader,:on=>:filename
  
  validates :node_id,presence: true
  validates :name,presence: true
  validates :display_name,presence: true
  #validates :thumbnail,presence: true
  validates :remark,presence: true


  after_save :update_cache_version
  after_destroy :update_cache_version
  def update_cache_version
    # 记录节点变更时间，用于清除缓存
    CacheVersion.materials_updated_at = Time.now.to_i
  end

  def indexed_changed?
    display_name_changed? || remark_changed?
  end

end

app/models/material_category.rb
class MaterialCategory < ApplicationRecord
		include BaseModel
    has_many :nodes
    # 缓存
    second_level_cache expires_in: 2.days
    
    scope :sorted, -> { order(sort: :desc) }
    def self.nodes
        Node.where("material_category_id IS NOT NULL").order(model_category_id: :desc)
    end
end

app/models/model.rb
class Model < ApplicationRecord
	include Searchable
  include BaseModel
  belongs_to :node

  
  mount_uploader :skp,SkpFileUploader,:on=>:filename
  mount_uploader :thumbnail,PhotoUploader,:on=>:filename

  validates :display_name,presence: true
  validates :node_id,presence: true
  validates :name,presence: true
  validates :remark,presence: true
  # validates :thumbnail,presence: true
  # validates :skp,presence: true

  after_save :update_cache_version
  after_destroy :update_cache_version
  def update_cache_version
    # 记录节点变更时间，用于清除缓存
    CacheVersion.models_updated_at = Time.now.to_i
  end

  def indexed_changed?
    display_name_changed? || remark_changed?
  end
end

app/models/model_category.rb
class ModelCategory < ApplicationRecord
		include BaseModel
    has_many :nodes
    second_level_cache expires_in: 2.days
    scope :sorted, -> { order(sort: :desc) }
    def self.nodes
        Node.where("model_category_id IS NOT NULL").order(model_category_id: :desc)
    end
end

app/models/node.rb
class Node < ApplicationRecord
	include BaseModel
  belongs_to :material_category, :touch => true 
  belongs_to :model_category, :touch => true 
  has_many   :materials
  has_many   :models

  scope :material_nodes, -> { where(model_category_id: nil) }
  scope :model_nodes,->{where(material_category_id: nil)}
  # 缓存
  second_level_cache expires_in: 2.days
  scope :sorted, -> { order(sort: :desc) }
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/config.yml")
  namespace Rails.env
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/models_controller.rb
module Api
  module V1
    class ModelsController < Api::V1::ApplicationController

      # 获取 Models 列表
      #
      # GET /api/v1/models
      # @return [Array<ModelSerializer>]
      def index
        @models = Model.all
        @meta = { total: Model.count }
      end

      ##
      # 获取单个 Model 详情
      #
      # GET /api/v1/model/:id
      # @return [ModelSerializer]
      def show
        @model = Model.find(params[:id])
      end
    end
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
	layout "upload", :only => [:new]
	before_action :get_categories,:only => [:index,:node,:node_category,:search,:new,:find_by_ids]
	def index
		if session[:last_model_node_id]
			@node = Node.find(session[:last_model_node_id])
			@models = @node.models.recent.page(params[:page])
		else
			@models = Model.recent.page(params[:page])
		end
		fresh_when([@model_categories, @models])
	end

  def node_category
    @node = ModelCategory.find(params[:id])
    @models = Model.include_column_ids('node_id',@node.nodes.ids)
    @models = @models.recent.page(params[:page])
    if stale?(etag: [@nodel, @model_categories,@models], template: 'models/index')
      render action: 'index'
    end
  end

	def node
		@node = Node.find(params[:id])
    @models = @node.models
    @models = @models.recent.page(params[:page])
    session[:last_model_node_id] = @node.id
    if stale?(etag: [@node, @model_categories,@models], template: 'models/index')
      render action: 'index'
    end
	end

	def find_by_ids
		ids = params[:ids]? params[:ids].split(',') : []
		@models = Model.find_by_ids(ids).recent.page(params[:page])
    respond_to do |format|
      format.js
    end
	end

	def search
    search_params = {
      query: {
        simple_query_string: {
          query: params[:q],
          default_operator: 'AND',
          minimum_should_match: '20%',
          fields: %w(display_name remark)
        }
      }
    }
    @models = Elasticsearch::Model.search(search_params, [Model]).page(params[:page])
    #if stale?(etag: ['search_models',@models], template: 'models/index')
    render action: 'index'
    #end
	end

	def all
		session[:last_model_node_id]=nil
		redirect_to models_path
	end

	def new
    @model = Model.new
  end

	def create
    @model = Model.new(model_params)
    respond_to do |format|
      if @model.save
        format.js
      else
        format.js
      end
    end
  end
	private 
	def get_categories
		@model_categories = ModelCategory.all.sorted
	end
	def model_params
    params.require(:model).permit(:name,:node_id,:skp,:remark,:thumbnail,:display_name)
  end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<div class="form-horizontal">
  <div class="container mt20 mlr10">
    <div class="row clearfix colxs">
    <div id='form-column' class="col-md-12 column">
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-2 col-xs-3 control-label">选择分类</label>
          <div class="col-sm-10 col-xs-9">
            <div class="input-select">
              <div class="updown">
                <div class="selectbox">请选择</div>
                <div class="dropdown" style="display: none;">
                  <div class="itemcontainer">
                    <% catch(['models_categories', @model_categories]) do%>
                    <%= render partial: "model_category", collection: @model_categories %>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%= form_for @model, remote: true do |f| %>
        <%= render "shared/error_messages", target: @model %>
        <input name="model[node_id]" id="model_node_id" type="hidden" value="">
        <div class="form-group">
          <label class="col-sm-2 col-xs-3 control-label">显示名称</label>
          <div class="col-sm-10 col-xs-9">
            <input type="text" class="form-control" name="model[display_name]" id="model_display_name" />
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 col-xs-3 control-label">模型名称</label>
          <div class="col-sm-10 col-xs-9">
            <input type="text" class="form-control" name="model[name]" id="model_name" />
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 col-xs-3 control-label">&emsp;预览图</label>
          <div class="col-sm-10 col-xs-9">
            <div>
              <%= f.file_field :thumbnail,class: 'imgUrl1',onchange: "document.getElementById('model_thumbnail_text').value=this.value" %>
            </div>
            <div class="upload-file">
              <input id="model_thumbnail_text"  type="text" value="选择预览图..." class="imgUrl2">
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 col-xs-3 control-label">模型文件</label>
          <div class="col-sm-10 col-xs-9">
            <div>
              <%= f.file_field :skp,class: 'imgUrl1',onchange: "document.getElementById('model_skp_text').value=this.value" %>
            </div>
            <div class="upload-file">
              <input id="model_skp_text"  type="text" value="选择模型..." class="imgUrl2">
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 col-xs-3 control-label">&emsp;&emsp;备注</label>
          <div class="col-sm-10 col-xs-9">
            <textarea name="model[remark]" id="model_remark" class="form-control"></textarea>
          </div>
        </div>

        <div class="btnsub">
          <div class="btn-sub">
            <button type="button" name="" class="btn btn-default">取 消</button>
            <button type="submit" name="commit" class="btn  btn-primary" data-disable-with="正在提交">上 传</button>
          </div>
        </div>
        <%end%>
      </div>
    </div>
  </div>

</div>
<div class="modal fade" tabindex="-1" role="dialog" id="myDialog" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">提示</h4>
      </div>
      <div class="modal-body">
        <p>创建成功......</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <%= link_to('继续上传',new_model_path,class:'btn btn-primary') %>
      </div>
    </div>
  </div>
</div>

app/views/models/_model.html.erb
<% cache([model]) do %>
		<li>
			<a href="#" title="<%=model.display_name%>" data-id="<%=model.id%>">
				<img src="<%=model.thumbnail.url(:lg)%>" alt="<%=model.display_name%>">
			</a>
			<span style='display:none'></span>
		</li>
<% end %>

app/views/models/_model_category.html.erb
<% cache([model_category]) do %>
	<dl>
		<dt ><%= model_category.name %></dt>
		<% model_category.nodes.each do |node| %>
			<dd data-id="<%=node.id%>" style="cursor:pointer">
				<%= node.name%>
			</dd>
		<% end %>
	</dl>
<% end %>

app/views/models/_warning_messages.html.erb
<div class="alert alert-warning" role="alert">
  <a class="close" data-dismiss='alert' href="#">×</a>
  <p><strong>警告</strong></p>
  	 当前场景中无本插件的模型
</div>

app/views/models/create.js.erb
<% if @model.errors.empty? %>
	$("#myDialog").modal('show');
<% else %>
  $('#form-column .alert').remove();
  $('#form-column').prepend('<%= j render("shared/error_messages", target: @model) %>');
<% end %>

app/views/models/find_by_ids.js.erb
<% if @models.empty? %>
	$('.ul-img-all .alert').remove();
  $('.ul-img-all').prepend('<%= j render("warning_messages") %>');
  $('.current_scene_models').removeClass('active');
<% else %>
	$(".ul-img-all").empty();
	<% @models.each do |model| %>
    $(".ul-img-all").append("<%= j(render 'model', model: model) %>")
	<% end %>
	$('.ul-img-all li').hover((function() {
	  var txt;
	  txt = $(this).find('img').attr('alt');
	  $(this).find('a').next('span').show().html(txt);
	  $(this).addClass('focusColor');
	}), function() {
	  $(this).find('a').next('span').hide();
	  $(this).removeClass('focusColor');
	});
	$("#models a").each(function(index) {
      $(this).click(function(event) {
        var id = $(this).data('id');
        if (id!=undefined){
          SC.Sketchup.callback("Model.dowload",{id: id});
          return false;
        }else{
          alert("非法链接");
          return false;            
        }
      });
   });
	$('#selectbox-model').text("场景中的模型");
	$('.current_scene_models').addClass('active');
<% end %>

app/views/models/index.html.erb
<% content_for :scripts do %>
<script type="text/javascript">
  $(document).ready(function(){
    $(".current_scene_models").click(function(event) {
      if($(this).is('.active')){
        $(this).removeClass('active');
        SC.Sketchup.callback('Window.last_history');
      }else{
        SC.Sketchup.callback('Model.current_scene_models',{last_history:"<%=request.url%>"});
        return false;
      }
    });
    $("#models a").each(function(index) {
      $(this).click(function(event) {
        var id = $(this).data('id');
        if (id!=undefined){
          SC.Sketchup.callback("Model.dowload",{id: id});
          return false;
        }else{
          alert("非法链接");
          return false;            
        }
      });
    });
  });
</script>
<% end %>

<!-- 模型 -->
<div class="material-model">
  <div class="container mt20">
    <div class="row clearfix">
      <!-- 搜索框 -->
      <div class="col-md-12 pr20">
        <div class="row clearfix">
          <div class="col-md-12">
            <%= form_for('', url: {action: "search"},method: "get") do |f| %>
            <div class="form-group bs-search">
              <% search_class = params[:q] ? 'form-control input-search bs-search-active' : 'form-control input-search' 
              style_class   = params[:q] ? "display: none;" : ''%>
              <%= f.text_field(:q,class: search_class,value: params[:q]) %>
              <span class="bs-placeholder" style="<%= style_class %>">
                <span class="serimg"></span>
                <span>搜索</span>
              </span>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-12 mb20 qhline">
        <div class="row marginone">
          <div class="col-md-6 col-sm-6 col-xs-6" data-turbolinks-permanent>
            <div class="updown">
              <div class="selectbox" id="selectbox-model"><%= @node?  @node.name : "全部"  %></div>
              <div class="dropdown" style="display: none;">
                <div class="itemcontainer">
                  <ul class="model-item">
                    <li class="item-title" data-url='/models/all' style="cursor:pointer"><a href='#'>全部</a></li>
                    <% cache ([@model_categories]) do%>
                    <%= render partial: "/model_categories/model_category", collection: @model_categories %>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6" data-turbolinks-permanent>
            <ul class="ul-img-select">
              <li>
                <a href="#" title="上一分类" id="pre_model"><span class="pre"></span></a>
              </li>
              <li>
                <a href="#" title="下一分类" id="next_model"><span class="next"></span></a>
              </li>
              <li class="current_scene_models">
                <a href="#" title="收藏"><span class="star"></span></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- 中间图片展示 -->
      <div class="col-md-12">
        <ul class="ul-img-all ul-img-all2 ul-img scroll-wrap" id='models'>
          <% cache(['models', @models]) do%>
          <%= render partial: "model", collection: @models %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-img clearfix" data-turbolinks="false">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="img-squared">
            <a href="#" title="小缩略图">
              <div class="small" id="small_mod"></div>
            </a>
            <a href="#" title="大缩略图">
              <div class="big-hover" id="big_mod"></div>
            </a>
          </div>
          <%= paginate @models,:theme=>'sketchup' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/models/new.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    $(function() {
      $('.btn.btn-default').click(function(event) {
        SC.Sketchup.callback("Window.close");
      });
      $(".dropdown").find('dt,dd').click(function(event) {
        var nodeId = $(this).data("id");
        if(nodeId==undefined){
          alert('请选择子分类!');
        }else{
          $(".flag").removeClass('hide');
          $(".selectbox").html($(this).text());
          $(".dropdown").slideUp();
          $(".selectbox").removeClass('open');
          $('.form-horizontal input[name="model[node_id]"]').val(nodeId);
        }
        return false;
        });
    });
  </script>
<% end %>
<div class="flag hide"></div>
<%= render 'form' %>