config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      get 'hello', to: 'root#hello'
      resources :nodes,only: [:index,:show] do
        collection do
          get :materials
          get :models
        end
      end
      resources :materials,only:[:index,:show]
      resources :models,only:[:index,:show]
    end
  end

  root to: 'materials#index'
  get 'materials/material_category:id',to: 'materials#node_category', as: 'node_category_materials'
  get 'materials/node:id', to: 'materials#node', as: 'node_materials'
  get 'models/model_category:id',to: 'models#node_category', as: 'node_category_models'
  get 'models/node:id', to: 'models#node', as: 'node_models'
  resources :materials,only:[:index,:new,:create] do
    collection do
      get :all
      get :search
      get :find_by_ids
    end
  end
  resources :models,only:[:index,:new,:create] do
    collection do
      get :all
      get :search
      get :find_by_ids
    end
  end
  resources :nodes,only:[:index]
  resources :categories,only:[:index]
  resources :home,only:[:index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  begin
    ActiveAdmin.routes(self) 
  rescue Exception => e
    
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount PgHero::Engine, at: "pghero"
  mount ExceptionTrack::Engine => "/exception-track"

end

app/models/material.rb
class Material < ApplicationRecord
	include Searchable
  include BaseModel
  belongs_to :node
  mount_uploader :texture,PhotoUploader,:on=>:filename
  mount_uploader :thumbnail,PhotoUploader,:on=>:filename
  
  validates :node_id,presence: true
  validates :name,presence: true
  validates :display_name,presence: true
  #validates :thumbnail,presence: true
  validates :remark,presence: true


  after_save :update_cache_version
  after_destroy :update_cache_version
  def update_cache_version
    # 记录节点变更时间，用于清除缓存
    CacheVersion.materials_updated_at = Time.now.to_i
  end

  def indexed_changed?
    display_name_changed? || remark_changed?
  end

end

app/controllers/api/v1/materials_controller.rb
module Api
  module V1
    class MaterialsController < Api::V1::ApplicationController

      # 获取 Materials 列表
      #
      # GET /api/v1/materials
      # @return [Array<MaterialSerializer>]
      def index
        @materials = Material.all
        @meta = { total: Material.count }
      end

      ##
      # 获取单个 Material 详情
      #
      # GET /api/v1/material/:id
      # @return [MaterialSerializer]
      def show
        @material = Material.find(params[:id])
      end
    end
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
	layout "upload", :only => [:new,:create]
	before_action :get_categories,:only => [:index,:node_category,:node,:search,:new,:find_by_ids]
	def index
		if session[:last_mat_node_id]
			@node = Node.find(session[:last_mat_node_id])
			unless @node.blank?
				@materials = @node.materials.recent.page(params[:page])
				session[:last_mat_node_id] = @node.id
			else
				@materials = Material.recent.page(params[:page])
			end
		else
			@materials = Material.recent.page(params[:page])
			session[:last_mat_page] = params[:page]
		end
		fresh_when([@material_categories, @materials])
	end

	def node_category
		@node = MaterialCategory.find(params[:id])
		@materials = Material.include_column_ids('node_id',@node.nodes.ids)
		@materials = @materials.recent.page(params[:page])
		if stale?(etag: [@nodel, @material_categories,@materials], template: 'materials/index')
      render action: 'index'
    end
	end

	def node
		@node = Node.find(params[:id])
    @materials = @node.materials
    @materials = @materials.recent.page(params[:page])
    session[:last_mat_node_id] = @node.id
		session[:last_mat_page]    = params[:page]
    if stale?(etag: [@node, @material_categories,@materials], template: 'materials/index')
      render action: 'index'
    end
	end

	def all
		session[:last_mat_node_id] = nil
		session[:last_mat_page]    = nil
		redirect_to materials_path
	end

	def find_by_ids
		ids = params[:ids]? params[:ids].split(',') : []
		@materials = Material.find_by_ids(ids).recent.page(params[:page])
  	respond_to do |format|
      format.js
    end
	end

	def search
    search_params = {
      query: {
        simple_query_string: {
          query: params[:q],
          default_operator: 'AND',
          minimum_should_match: '20%',
          fields: %w(display_name remark)
        }
      }
    }
    @materials = Elasticsearch::Model.search(search_params, [Material]).page(params[:page])
    #if stale?(etag: ['search_materials',@materials], template: 'materials/index')
      render action: 'index'
    #end
	end

	def new
    @material = Material.new
  end

	def create
    @material = Material.new(material_params)
    respond_to do |format|
      if @material.save
        format.js
      else
        format.js
      end
    end
  end
	private 
	# def get_page
	# 	@page     = session[:last_mat_page].to_i
	# 	new_page  = params[:page].to_i
	# 	new_page =1 if new_page ==0
	# 	return if new_page == @page
	# 	if (new_page-@page).abs==1
	# 		@page = new_page
	# 	end
	# end
	def get_categories
		@material_categories = MaterialCategory.all.sorted
	end
	def material_params
    params.require(:material).permit(:name,:node_id,:color,:alpha,:texture,:remark,:thumbnail,:display_name)
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<div class="form-horizontal">
  <div class="container mt20 mlr10">
    <div class="row clearfix colxs">
    <div id='form-column' class="col-md-12 column">
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-2 col-xs-3 control-label">选择分类</label>
          <div class="col-sm-10 col-xs-9">
            <div class="input-select">
              <div class="updown">
                <div class="selectbox">请选择</div>
                <div class="dropdown" style="display: none;">
                  <div class="itemcontainer">
                    <% catch(['materials_categories', @material_categories]) do%>
                    <%= render partial: "material_category", collection: @material_categories %>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%= form_for @material, remote: true do |f| %>
        <%= render "shared/error_messages", target: @material %>
        <input name="material[node_id]" id="material_node_id" type="hidden" value="">
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 col-xs-3 control-label">显示名称</label>
          <div class="col-sm-10 col-xs-9">
            <input type="text" class="form-control" name="material[display_name]" id="material_display_name" />
          </div>
        </div>

        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 col-xs-3 control-label">材料名称</label>
          <div class="col-sm-10 col-xs-9">
            <input type="text" class="form-control" name="material[name]" id="material_name" />
          </div>
        </div>

        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 col-xs-3 control-label">&emsp;预览图</label>
          <div class="col-sm-10 col-xs-9">
            <div>
               <%= f.file_field :thumbnail,class: 'imgUrl1',onchange: "document.getElementById('material_thumbnail_text').value=this.value" %>
            </div>
            <div class="upload-file">
              <input id="material_thumbnail_text"  type="text" value="选择预览图..." class="imgUrl2">
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 col-xs-3 control-label">贴图文件</label>
          <div class="col-sm-10 col-xs-9">
            <div>
              <%= f.file_field :texture,class: 'imgUrl1',onchange: "document.getElementById('material_texture_text').value=this.value" %>
            </div>
            <div class="upload-file">
              <input id="material_texture_text"  type="text" value="选择贴图..." class="imgUrl2">
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 col-xs-3 control-label">&emsp;颜色值</label>
          <div class="col-sm-10 col-xs-9">
            <div class="input-group" id="cp2">
              <input type="text" class="form-control" name="material[color]" id="material_color" placeholder="" value="#ae7b00">
              <span class="input-group-addon colorselect"><img src=<%= image_url('kong.png')%>  alt=""></span>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 col-xs-3 control-label">&emsp;透明度</label>
          <div class="col-sm-10 col-xs-9">
            <div class="input-group">
              <span class="input-group-addon colorselect2"><img src=<%= image_url('minus.png')%>  alt=""></span>
              <input type="text" class="form-control inputvalue" name="material[alpha]" id="material_alpha" value="100">
              <span class="input-group-addon colorselect3"><img src=<%= image_url('plus.png')%>  alt=""></span>
            </div>
          </div>
        </div>



        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 col-xs-3 control-label">&emsp;&emsp;备注</label>
          <div class="col-sm-10 col-xs-9">
            <textarea name="material[remark]" id="material_remark" class="form-control"></textarea>
          </div>
        </div>

        <div class="btnsub">
          <div class="btn-sub">
            <button type="button" name="" class="btn btn-default">取 消</button>
            <button type="submit" name="commit" class="btn  btn-primary" data-disable-with="正在提交">上 传</button>
          </div>
        </div>
        <%end%>
      </div>
    </div>
  </div>

</div>
<div class="modal fade" tabindex="-1" role="dialog" id="myDialog" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">提示</h4>
      </div>
      <div class="modal-body">
        <p>创建成功......</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <%= link_to('继续上传',new_material_path,class:'btn btn-primary') %>
      </div>
    </div>
  </div>
</div>

app/views/materials/_material.html.erb
<% cache([material]) do %>
	<li>
		<a href="#" title="<%=material.display_name%>" data-id="<%=material.id%>" >
			<% 
				if material.thumbnail.class == Hashie::Mash
					url = material.thumbnail['url']
				else
					url = material.thumbnail_url
				end
			%>
			<% unless url %>
			<img src="<%=image_url('color_img.png')%>"" alt="<%=material.display_name%>" style="background-color: <%=material.color%>;" >
			<%else%>
				<img src="<%=material.thumbnail.url(:lg)%>" alt="<%=material.display_name%>">
			<%end%>
		</a>
		<span style='display:none'></span>
	</li>
<% end %>

app/views/materials/_material_category.html.erb
<% cache([material_category]) do %>
	<dl>
		<dt><%= material_category.name %></dt>
		<% material_category.nodes.each do |node| %>
			<dd data-id="<%=node.id%>" style="cursor:pointer">
				<%= node.name%>
			</dd>
		<% end %>
	</dl>
<% end %>

app/views/materials/_warning_messages.html.erb
<div class="alert alert-warning" role="alert">
  <a class="close" data-dismiss='alert' href="#">×</a>
  <p><strong>警告</strong></p>
  	当前场景中无本插件的材质
</div>

app/views/materials/create.js.erb
<% if @material.errors.empty? %>
	$("#myDialog").modal('show');
<% else %>
  $('#form-column .alert').remove();
  $('#form-column').prepend('<%= j render("shared/error_messages", target: @material) %>');
<% end %>

app/views/materials/find_by_ids.js.erb
<% if @materials.empty? %>
	$('.ul-img-all .alert').remove();
  $('.ul-img-all').prepend("<%= j render('warning_messages') %>");
  $('.current_scene_materials').removeClass('active');
<% else %>
	$(".ul-img-all").empty();
	<% @materials.each do |material| %>
    $(".ul-img-all").append("<%= j(render 'material', material: material) %>")
	<% end %>
	$('.ul-img-all li').hover((function() {
	  var txt;
	  txt = $(this).find('img').attr('alt');
	  $(this).find('a').next('span').show().html(txt);
	  $(this).addClass('focusColor');
	}), function() {
	  $(this).find('a').next('span').hide();
	  $(this).removeClass('focusColor');
	});
	$("#materials a").each(function(index) {
    $(this).click(function(event) {
      var id = $(this).data('id');
      if (id!=undefined){
        SC.Sketchup.callback("Material.dowload",{id: id});
        return false;
      }else{
        alert("非法链接");    
        return false;        
      }
    });
  });

	$('#selectbox-material').text("场景中的材质");
	$('.current_scene_materials').addClass('active');
<% end %>

app/views/materials/index.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".current_scene_materials").click(function(event) {
        if($(this).is('.active')){
          $(this).removeClass('active');
          SC.Sketchup.callback('Window.last_history');
        }else{
          SC.Sketchup.callback('Material.current_scene_materials',{last_history:"<%=request.url%>"});
        }
        return false;
      });
      $("#materials a").each(function(index) {
        $(this).click(function(event) {
          var id = $(this).data('id');
          if (id!=undefined){
            SC.Sketchup.callback("Material.dowload",{id: id});
            return false;
          }else{
            alert("非法链接");    
            return false;        
          }
        });
      });
    });
  </script>
<% end %>
<!-- 材质 -->
<div class="material-model">
  <div class="container mt20 ">
    <div class="row clearfix">
      <!-- 搜索框 -->
      <div class="col-md-12 pr20">
        <div class="row clearfix">
          <div class="col-md-12">
            <%= form_for('', url: {action: "search"},method: "get") do |f| %>
              <div class="form-group bs-search" >
                  <% search_class = params[:q] ? 'form-control input-search bs-search-active' : 'form-control input-search' 
                    style_class   = params[:q] ? "display: none;" : ''%>
                  <%= f.text_field(:q,class: search_class,value: params[:q]) %>
                  <span class="bs-placeholder" style="<%= style_class %>">
                    <span class="serimg"  ></span>
                    <span>搜索</span>
                  </span>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-12 mb20 qhline">
        <div class="row marginone">
          <div class="col-md-6 col-sm-6 col-xs-6" data-turbolinks-permanent>
            <div class="updown">
              <div class="selectbox" id="selectbox-material"><%= @node?  @node.name : "全部"  %></div>
              <div class="dropdown" style="display: none;">
                <div class="itemcontainer" >
                  <ul class="material-item">
                    <li class="item-title" data-url='/materials/all' style="cursor:pointer"><a href='#'>全部</a></li>
                    <% cache ([@material_categories]) do%>
                      <%= render partial: "/material_categories/material_category", collection: @material_categories %>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6" data-turbolinks-permanent>
            <ul class="ul-img-select">
              <li>
                <a href="#" title="上一使用过的分类" id="pre_material"><span class="pre" ></span></a>
              </li>
              <li>
                <a href="#" title="下一使用过的分类" id="next_material"><span class="next" ></span></a>
              </li>
              <li class="current_scene_materials">
                <a href="#" title="当前场景使用的材质"><span class="star"></span></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- 中间图片展示 -->
      <div class="col-md-12">
        <ul class="ul-img-all ul-img-all1 ul-img scroll-wrap" id='materials'>
          <% cache(['materials', @materials]) do%>
            <%= render partial: "material", collection: @materials %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-img clearfix" data-turbolinks="false">
    <div class="container">
      <div class="row">
        <div class="col-md-12" >
          <div class="img-squared">
            <a href="#" title="小缩略图">
              <div class="small" id="small_mat"></div>
            </a>
            <a href="#" title="大缩略图">
              <div class="big-hover" id="big_mat"></div>
            </a>
          </div>
          <%= paginate @materials,:theme=>'sketchup'  %>
        </div>
      </div>
    </div>
  </div>
</div>



app/views/materials/new.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    $(function() {
      $('#cp2').colorpicker();
      $('.btn.btn-default').click(function(event) {
      	SC.Sketchup.callback("Window.close");
      });
      $(".dropdown").find('dt,dd').click(function(event) {
        var nodeId = $(this).data("id");
        if(nodeId==undefined){
          alert('请选择子分类!');
        }else{
          $(".flag").removeClass('hide');
          $(".selectbox").html($(this).text());
          $(".dropdown").slideUp();
          $(".selectbox").removeClass('open');
          $('.form-horizontal input[name="material[node_id]"]').val(nodeId);
        }
        return false;
    	});
    });
  </script>
<% end %>
<div class="flag hide"></div>
<%= render 'form' %>

