config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      get 'hello', to: 'root#hello'
      resources :nodes,only: [:index,:show] do
        collection do
          get :materials
          get :models
        end
      end
      resources :materials,only:[:index,:show]
      resources :models,only:[:index,:show]
    end
  end

  root to: 'materials#index'
  get 'materials/material_category:id',to: 'materials#node_category', as: 'node_category_materials'
  get 'materials/node:id', to: 'materials#node', as: 'node_materials'
  get 'models/model_category:id',to: 'models#node_category', as: 'node_category_models'
  get 'models/node:id', to: 'models#node', as: 'node_models'
  resources :materials,only:[:index,:new,:create] do
    collection do
      get :all
      get :search
      get :find_by_ids
    end
  end
  resources :models,only:[:index,:new,:create] do
    collection do
      get :all
      get :search
      get :find_by_ids
    end
  end
  resources :nodes,only:[:index]
  resources :categories,only:[:index]
  resources :home,only:[:index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  begin
    ActiveAdmin.routes(self) 
  rescue Exception => e
    
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount PgHero::Engine, at: "pghero"
  mount ExceptionTrack::Engine => "/exception-track"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name=“renderer” content=“webkit”>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SC100</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload'%>
</head>
<body>

  <div class="head">
      <div class="container">
          <div class="row clearfix">
              <!-- 导航栏 切换-->
              <div class="col-md-12">
                  <div class="row clearfix">
                      <div class="col-md-8 col-sm-8 col-xs-8">
                          <ul class="nav-img">
                          		<%= render_list_items do |li|
                          			li<<link_to(materials_path,title: '材质') do
                          				content_tag(:span,'',class:'figure')
                          			end
                          			li<<link_to(models_path,title: '模型') do
                          				content_tag(:span,'',class:'model')
                          			end
                          		end%>
                          </ul>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
   <div class="flag hide"></div>
	<%= yield %>
  <%= yield :scripts %>
	<script type="text/javascript">
	  $(function() {
	    var h = $("html,body").height() - 210;
	    $(".scroll-wrap").height(h);
	  })
  </script>
</body>
</html>

app/views/layouts/upload.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name=“renderer” content=“webkit”>
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SC100</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload'%>
</head>
<body>
	<%= yield %>
	<%= yield :scripts %>
    <div class="textceter"  data-turbolinks-permanent>
        SC100-v1.0.0
    </div>
</body>
</html>